[versions]
kotlin = "2.4.10"
publish = "0.28.0"
dokka = "2.2.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
vanniktech-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

[bundles]
pluginsForBuildSrc = [
    "kotlin-gradle-plugin",
    "vanniktech-maven-publish",
    "dokka-gradle-plugin",
]
